# Entropia Universe settings ini file
target_file = "/home/void/.local/share/Steam/steamapps/compatdata/3642750/pfx/drive_c/users/steamuser/Documents/Entropia Universe/chat.log"
fifo_pipe = /tmp/min_pipe
poll_delay_ms = 300
avatarname = Deux Pelleman Ex
blockentries = "#calytrade", "#trade", "#arktrade", "#Rookie"
